from setuptools import setup, Extension, find_packages

ext_modules = [
    Extension(
        "latpy.core._core",
        sources=[
            "latpy/core/src/globals.cpp",
            "latpy/core/src/compute_gso.cpp",
            "latpy/core/src/compute_cf.cpp",
            "latpy/core/src/compute_r.cpp",
            "latpy/core/src/block_qr.cpp",
            "latpy/core/src/volume.cpp",
            "latpy/core/src/sl.cpp",
            "latpy/core/src/pot.cpp",
            "latpy/core/src/hf.cpp",
            "latpy/core/src/rhf.cpp",
            "latpy/core/src/od.cpp",
            "latpy/core/src/is_size.cpp",
            "latpy/core/src/is_weakly_lll.cpp",
            "latpy/core/src/is_seysen.cpp",
            "latpy/core/src/is_weakly_deep_lll.cpp"
        ],
        language="c++",
        extra_compile_args=[
            "-O3",
            "-fopenmp",
            "-march=native",
            "-funroll-loops",
            "-DEIGEN_INITIALIZE_MATRICES_BY_NAN",
            "-DEIGEN_NO_DEBUG=0"
        ],
        extra_link_args=[
            "-fopenmp",
            "-lntl",
            "-DEIGEN_INITIALIZE_MATRICES_BY_NAN",
            "-DEIGEN_NO_DEBUG=0"
        ],
        include_dirs=[
            "latpy/core/include"
        ]
    ),
    Extension(
        "latpy.reduction._reduction",
        sources=[
            "latpy/core/src/globals.cpp",
            "latpy/core/src/compute_gso.cpp",
            "latpy/core/src/compute_cf.cpp",
            "latpy/core/src/compute_r.cpp",
            "latpy/core/src/block_qr.cpp",
            "latpy/core/src/volume.cpp",
            "latpy/core/src/sl.cpp",
            "latpy/core/src/rhf.cpp",
            "latpy/reduction/src/deep_insertion.cpp",
            "latpy/reduction/src/dual_deep_insertion.cpp",
            "latpy/reduction/src/update_swap_gso.cpp",
            "latpy/reduction/src/update_swap_r.cpp",
            "latpy/reduction/src/update_deep_insertion_gso.cpp",
            "latpy/reduction/src/update_deep_insertion_r.cpp",
            "latpy/reduction/src/update_dual_deep_insertion_gso.cpp",
            "latpy/reduction/src/pot_enum.cpp",
            "latpy/reduction/src/lagrange.cpp",
            "latpy/reduction/src/size.cpp",
            "latpy/reduction/src/LLL.cpp",
            "latpy/reduction/src/deep_LLL.cpp",
            "latpy/reduction/src/L2.cpp",
            "latpy/svp/src/globals.cpp",
            "latpy/svp/src/coeff_pruning.cpp",
            "latpy/svp/src/enum_sv.cpp",
            "latpy/svp/src/qr_enum_sv.cpp",
            "latpy/reduction/src/bkz.cpp",
            "latpy/reduction/src/seysen.cpp",
            "latpy/reduction/src/seysen_unimodular.cpp",
            "latpy/reduction/src/qr_lll.cpp",
            "latpy/reduction/src/qr_deep_lll.cpp",
            "latpy/reduction/src/deep_l2.cpp",
            "latpy/reduction/src/pot_lll.cpp",
            "latpy/reduction/src/deep_bkz.cpp",
            "latpy/reduction/src/pot_bkz.cpp",
            "latpy/reduction/src/qr_bkz.cpp",
            "latpy/reduction/src/qr_deep_bkz.cpp",
            "latpy/reduction/src/dual_pot_lll.cpp",
            "latpy/reduction/src/dual_deep_lll.cpp"
        ],
        language="c++",
        extra_compile_args=[
            "-O3",
            "-fopenmp",
            "-march=native",
            "-funroll-loops",
            "-DEIGEN_INITIALIZE_MATRICES_BY_NAN",
            "-DEIGEN_NO_DEBUG=0"
        ],
        extra_link_args=[
            "-fopenmp",
            "-lntl",
            "-DEIGEN_INITIALIZE_MATRICES_BY_NAN",
            "-DEIGEN_NO_DEBUG=0"
        ],
        include_dirs=[
            "latpy/reduction/include",
            "latpy/core/include",
            "latpy/svp/include"
        ]
    ),
    Extension(
        "latpy.svp._svp",
        sources=[
            "latpy/core/src/globals.cpp",
            "latpy/core/src/compute_gso.cpp",
            "latpy/svp/src/globals.cpp",
            "latpy/svp/src/coeff_pruning.cpp",
            "latpy/svp/src/enum_sv.cpp"
        ],
        language="c++",
        extra_compile_args=[
            "-O3",
            "-fopenmp",
            "-march=native",
            "-funroll-loops",
            "-DEIGEN_INITIALIZE_MATRICES_BY_NAN",
            "-DEIGEN_NO_DEBUG=0"
        ],
        extra_link_args=[
            "-fopenmp",
            "-lntl",
            "-DEIGEN_INITIALIZE_MATRICES_BY_NAN",
            "-DEIGEN_NO_DEBUG=0"
        ],
        include_dirs=[
            "latpy/svp/include",
            "latpy/core/include"
        ]
    )
]

setup(
    name="latpy",
    version="0.1.0",
    description="Lattice reduction algorithms with C++ backend",
    packages=find_packages(),
    ext_modules=ext_modules,
    python_requires=">=3.8",
    package_data={
        "latpy": ["svp_challenge_list/*.txt"],
    },
    include_package_data=True
)
