from setuptools import setup, Extension

latpy = [
    Extension(
        "latpy.core._core",
        sources=[
            "latpy/core/src/globals.cpp",
            "latpy/core/src/compute_gso.cpp",
            "latpy/core/src/volume.cpp",
            "latpy/core/src/sl.cpp",
            "latpy/core/src/pot.cpp",
            "latpy/core/src/hf.cpp",
            "latpy/core/src/rhf.cpp",
            "latpy/core/src/od.cpp"
        ],
        language="c++",
        extra_compile_args=[
            "-O3",
            "-fopenmp",
            "-march=native",
            "-funroll-loops",
            "-lntl"
        ],
        extra_link_args=[
            "-fopenmp",
            "-lntl"
        ],
        include_dirs=[
            "latpy/core/include"
        ]
    ),
    Extension(
        "latpy.reduction._reduction",
        sources=[
            "latpy/reduction/src/globals.cpp",
            "latpy/reduction/src/compute_gso.cpp",
            "latpy/reduction/src/compute_cf.cpp",
            "latpy/reduction/src/deep_insertion.cpp",
            "latpy/reduction/src/rhf.cpp",
            "latpy/reduction/src/sl.cpp",
            "latpy/reduction/src/update_swap_gso.cpp",
            "latpy/reduction/src/update_deep_insertion_gso.cpp",
            "latpy/reduction/src/lagrange.cpp",
            "latpy/reduction/src/size.cpp",
            "latpy/reduction/src/LLL.cpp",
            "latpy/reduction/src/deep_LLL.cpp",
            "latpy/reduction/src/L2.cpp"
        ],
        language="c++",
        extra_compile_args=[
            "-O3",
            "-fopenmp",
            "-march=native",
            "-funroll-loops",
            "-lntl"
        ],
        extra_link_args=[
            "-fopenmp",
            "-lntl"
        ],
        include_dirs=[
            "latpy/reduction/include"
        ]
    )
]

setup(
    name="latpy",
    version="0.1.0",
    description="Example ctypes-based library",
    packages=["latpy"],
    ext_modules=latpy,
    python_requires=">=3.8",
)
